#ifndef OPENRIDE_RIDE_PLANNER_H
#define OPENRIDE_RIDE_PLANNER_H

typedef enum OpenRideRidePlannerMode {
    OPENRIDE_RIDE_PLANNER_ROUTE = 0,
    OPENRIDE_RIDE_PLANNER_LOOP
} OpenRideRidePlannerMode;

typedef enum OpenRideRidePlannerBusy {
    OPENRIDE_RIDE_PLANNER_IDLE = 0,
    OPENRIDE_RIDE_PLANNER_CALCULATING_ROUTE,
    OPENRIDE_RIDE_PLANNER_GENERATING_LOOPS
} OpenRideRidePlannerBusy;

#endif
