#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STB_DIR="$ROOT/vendor/stb"
FONT_DIR="$ROOT/vendor/ui-font"

STB_COMMIT="2c980bb59875b0d32144a71867fbdebb2f77cd20"
FONTS_COMMIT="352f6b7d9d6cc4fa9e242b931291d31b21a6dc84"

STB_URL="https://raw.githubusercontent.com/nothings/stb/${STB_COMMIT}/stb_truetype.h"
FONT_URL="https://raw.githubusercontent.com/google/fonts/${FONTS_COMMIT}/ofl/roboto/Roboto%5Bwdth%2Cwght%5D.ttf"
LICENSE_URL="https://raw.githubusercontent.com/google/fonts/${FONTS_COMMIT}/ofl/roboto/OFL.txt"

mkdir -p "$STB_DIR" "$FONT_DIR"

echo "OpenRide UI font bootstrap"
echo "- stb_truetype: ${STB_COMMIT}"
echo "- Roboto: ${FONTS_COMMIT}"

curl -fL --retry 3 "$STB_URL" -o "$STB_DIR/stb_truetype.h"
curl -fL --retry 3 "$FONT_URL" -o "$FONT_DIR/Roboto.ttf"
curl -fL --retry 3 "$LICENSE_URL" -o "$FONT_DIR/OFL.txt"

python3 - "$FONT_DIR/Roboto.ttf" "$FONT_DIR/roboto_data.inc" <<'PY'
from pathlib import Path
import sys

source = Path(sys.argv[1])
target = Path(sys.argv[2])
data = source.read_bytes()
if len(data) < 100_000:
    raise SystemExit(f"Roboto.ttf unexpectedly small: {len(data)} bytes")

with target.open("w", encoding="utf-8") as out:
    out.write("/* Generated by scripts/bootstrap_ui_font.sh. Do not edit. */\n")
    out.write("static const unsigned char openride_ui_font_data[] = {\n")
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        out.write("    ")
        out.write(", ".join(f"0x{value:02x}" for value in chunk))
        out.write(",\n")
    out.write("};\n")

print(f"Generated {target} ({len(data)} font bytes)")
PY

echo "OK: UI font dependencies ready"
